This is an analysis of the *San Francisco Salaries* dataset acquired from the following link at [Kaggle](https://www.kaggle.com/datasets/kaggle/sf-salaries?resource=download).

THe data is for San Francisco city employees from 2011-2014. This allows for a comparisons in one broad category: how compensation is distributed and how it changed over the four-year period. This encompases a variety of aspects.

Compensation distribution can refer to the whole government budger and within specific groups or positions. For example, looking at what portion of a position's compensation is overtime, and what portion of the whole budget goes towards IT Workers in general.

In [1]:
import sqlite3 as sql
import pandas as pd

In [2]:
con = sql.connect("Salaries.sqlite")
cur = con.cursor()

In [3]:
query = "SELECT name FROM sqlite_master WHERE type='table';"
cur.execute(query)
tables = cur.fetchall()

In [4]:
columnDict = {}

for i,table in enumerate(tables):
    query = "SELECT * FROM %s;" % table
    cur.execute(query)
    cols = list(cur.description)
    valuelist = []
    for j, col in enumerate(cols):
        collist = list(col)
        valuelist.append(collist[0])
    columnDict[table] = valuelist

columnDict

{('Salaries',): ['Id',
  'EmployeeName',
  'JobTitle',
  'BasePay',
  'OvertimePay',
  'OtherPay',
  'Benefits',
  'TotalPay',
  'TotalPayBenefits',
  'Year',
  'Notes',
  'Agency',
  'Status']}

In [5]:
query = """ SELECT DISTINCT Year from Salaries"""
cur.execute(query)
cur.fetchall()

[(2011,), (2012,), (2013,), (2014,)]

In [6]:
query = """ SELECT Year, COUNT(Year) from Salaries GROUP By Year"""
cur.execute(query)
cur.fetchall()

[(2011, 36159), (2012, 36766), (2013, 37606), (2014, 38123)]

In [7]:
query = """ SELECT DISTINCT Notes from Salaries"""
cur.execute(query)
cur.fetchall()

[('',)]

In [8]:
query = """ SELECT DISTINCT Agency from Salaries"""
cur.execute(query)
cur.fetchall()

[('San Francisco',)]

In [9]:
query = """ SELECT DISTINCT Status from Salaries"""
cur.execute(query)
cur.fetchall()

[('',), ('PT',), ('FT',)]

In [10]:
query = """ SELECT Status, COUNT(Status) from Salaries GROUP By Status"""
cur.execute(query)
cur.fetchall()

[('', 110535), ('FT', 22334), ('PT', 15785)]

In [11]:
query = """SELECT DISTINCT JobTitle from Salaries"""
cur.execute(query)
cur.fetchmany(5)

[('GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',),
 ('CAPTAIN III (POLICE DEPARTMENT)',),
 ('WIRE ROPE CABLE MAINTENANCE MECHANIC',),
 ('DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)',),
 ('ASSISTANT DEPUTY CHIEF II',)]

In [12]:
query = """SELECT COUNT(DISTINCT JobTitle) from Salaries"""
cur.execute(query)
cur.fetchmany(5)

[(2159,)]

In [13]:
query = """ SELECT DISTINCT Status from Salaries"""
cur.execute(query)
cur.fetchall()

[('',), ('PT',), ('FT',)]

In [14]:
query = """ SELECT MIN(BasePay), MAX(BasePay), AVG(BasePay) from Salaries"""
cur.execute(query)
cur.fetchall()

[(-166.01, 'Not Provided', 66053.72928807836)]

In [15]:
query="Select JobTitle,BasePay from Salaries where BasePay < 0"
cur.execute(query)
cur.fetchall()

[('Junior Clerk', -166.01),
 ('Junior Clerk', -121.63),
 ('Junior Clerk', -109.22),
 ('Junior Clerk', -106.6),
 ('Junior Clerk', -101.88),
 ('Junior Clerk', -93.14),
 ('Junior Clerk', -87.38),
 ('Junior Clerk', -75.67),
 ('Junior Clerk', -59.59),
 ('Junior Clerk', -30.58),
 ('Clerk', -9.5)]

In [16]:
query="Select Count(JobTitle) from Salaries where JobTitle in ('Junior Clerk')"
cur.execute(query)
cur.fetchall()

[(596,)]

In [17]:
query = """ SELECT MIN(OvertimePay), MAX(OvertimePay), AVG(OvertimePay) from Salaries where OvertimePay Not in ('Not Provided')"""
cur.execute(query)
cur.fetchall()

[(-0.01, 245131.88, 5066.059886444668)]

In [18]:
query="Select JobTitle,OvertimePay from Salaries where OvertimePay < 0"
cur.execute(query)
cur.fetchall()

[('Senior Eligibility Worker', -0.01)]

In [19]:
query = """ SELECT MIN(OtherPay), MAX(OtherPay), AVG(OtherPay) from Salaries where OtherPay Not in ('Not Provided')"""
cur.execute(query)
cur.fetchall()

[(-7058.59, 400184.25, 3648.767296804574)]

In [20]:
query="Select JobTitle,OtherPay from Salaries where OtherPay < 0"
cur.execute(query)
cur.fetchall()

[('IS Business Analyst-Principal', -7058.59),
 ('Custodial Supervisor', -9.6),
 ('Gardener', -46.76),
 ('Special Nurse', -50.19),
 ('Counselor, Log Cabin Ranch', -618.13)]

In [21]:
query = """ SELECT MIN(Benefits), MAX(Benefits), AVG(Benefits) from Salaries where Benefits Not in ('Not Provided')"""
cur.execute(query)
cur.fetchall()

[(-33.89, '', 18924.742068146654)]

In [22]:
query="Select JobTitle,Benefits from Salaries where Benefits < 0"
cur.execute(query)
cur.fetchall()

[('Police Officer 3', -2.73),
 ('Police Officer 3', -8.2),
 ('Police Officer 3', -33.89),
 ('Secretary 2', -13.8)]

In [23]:
query = """ SELECT MIN(TotalPay), MAX(TotalPay), AVG(TotalPay) from Salaries"""
cur.execute(query)
cur.fetchall()

[(-618.13, 567595.43, 74768.32197169265)]

In [24]:
query = """ SELECT MIN(TotalPayBenefits), MAX(TotalPayBenefits), AVG(TotalPayBenefits) from Salaries"""
cur.execute(query)
cur.fetchall()

[(-618.13, 567595.43, 93692.55481056681)]

# Data Exploration

There are some strange outliers such as jobs with negative base pay that will likely pop up as the exploration and analysis continues.

With the broad strokes established, mainly what possible values there are for each category, the focus can be shifted on comparing and contrasting different groups of employees. Most of these are curiousities outside of a handful.

The benefits will be looked at over time, as well as the distribution of job titles and if they change in name. Some positions may be renamed and won't be picked up by the **LIKE** command paramaters set up. 

I'll be looking at the following:

* **Law Enforcement**: by looking at the strings *Police* and *Sheriff* I can see the Law Enforcement wages paid by the city.
* **Fire Department**: By taking a look at the string *Fire* I can see how much is spent on the Fire Department in terms of wages.
* **Mayor**: by querying 'Mayor' to take a look at the mayor and their staff.
* **Healthcare**: This one is a variety of strings that are cut off to bring in the largest variety of job titles. The list is *nurs* (gets nurse and nursery), *medical*, *health*, *dent*, *pharma* (pharmacy and pharmacist), *Physician*, and *Social Work*. This should get most healthcare workers though with so many strings it will probably get a few incorrect ones which is why I will also try to avoid the strings *resources* and *examiner*. 
* **Information Science**: All of the IT/IS positions start with 'IS' so looking for that with a space afterwards should get all of those positions without having to filter too many other job titles.
* **Justice**: *Defender* should pick up Public Defenders and *court* should pick up most who work at the court. Judge did not seem to get many results which is strange, and even looking for it directly did not give any results aside from a secretary.
* **Engineers and Scientists**: Looking at the strings *bio*, *chem*, *research* and *engineer* should get all the relevant job titles. This is to see how much money is spent on research, development, and engineers in general.
* **Planning**: Looking at the string *plann* should get all job titles related to urban planning.
* **Technicians and Mechanics**: *automotive*, *Electr*, *mech*, *plumb* should get all handymen, mechanics, and technicians. This is to see how much is spent on maintenance work and similar tasks.
* **Clerks**: *clerk* and *secretar* should bring up all clerks, secretaries and other clerical staff to see how much is spent on office staff.

In [25]:
query = """SELECT JobTitle, SUM(TotalPayBenefits), Year from Salaries WHERE JobTitle LIKE '%Judge%'"""
cur.execute(query)
cur.fetchall()

[('SECRETARY TO THE PRESIDING JUDGE', 2904666.62, 2011)]

## Law Enforcement Jobs

In [ ]:
query = """SELECT JobTitle, SUM(TotalPayBenefits), AVG(TotalPayBenefits), COUNT(JobTitle), Year from Salaries 
WHERE JobTitle LIKE '%Police%' OR JobTitle LIKE '%Sheriff%' 
Group by JobTitle Order by JobTitle"""
cur.execute(query)
cur.fetchall()

[('AIRPORT POLICE SERVICES AIDE', 11244297.15, 60129.93128342246, 187, 2011),
 ('ASSISTANT INSPECTOR (POLICE DEPARTMENT)', 188999.2, 188999.2, 1, 2011),
 ('ASSISTANT INSPECTOR II (POLICE DEPARTMENT)',
  1508888.61,
  150888.861,
  10,
  2011),
 ('ASSISTANT INSPECTOR III (POLICE DEPARTMENT)',
  1374040.94,
  152671.21555555554,
  9,
  2011),
 ('ASSISTANT SHERIFF', 189675.09, 94837.545, 2, 2011),
 ('Assistant Sheriff', 767179.29, 191794.8225, 4, 2012),
 ('CAPTAIN III (POLICE DEPARTMENT)', 7836004.05, 211783.89324324325, 37, 2011),
 ('CHIEF DEPUTY SHERIFF', 503875.24, 167958.41333333333, 3, 2011),
 ('CHIEF OF POLICE', 267992.59, 267992.59, 1, 2011),
 ('COMMANDER III, (POLICE DEPARTMENT)',
  1435955.55,
  205136.50714285715,
  7,
  2011),
 ('Chief Deputy Sheriff', 2181134.48, 218113.448, 10, 2012),
 ('Chief of Police', 1235196.8, 411732.26666666666, 3, 2012),
 ('Community Police Services Aide', 51794326.06, 92655.32389982112, 559, 2012),
 ('DEPUTY CHIEF III (POLICE DEPARTMENT)',
  1250132.44,
  250026.48799999998,
  5,
  2011),
 ('DEPUTY SHERIFF', 64951787.99, 94820.12845255475, 685, 2011),
 ('Deputy Sheriff', 276251014.41, 142913.0959182618, 1933, 2012),
 ('Deputy Sheriff (SFERS)', 1981418.08, 123838.63, 16, 2014),
 ('Deputy Sheriff 1', 5015902.5, 64306.442307692305, 78, 2012),
 ('INSPECTOR II, (POLICE DEPARTMENT)',
  432848.20999999996,
  144282.73666666666,
  3,
  2011),
 ('INSPECTOR III, (POLICE DEPARTMENT)',
  24968457.92,
  154126.28345679014,
  162,
  2011),
 ('INSPECTOR, (POLICE DEPARTMENT)', 318997.97, 159498.985, 2, 2011),
 ('INSTITUTIONAL POLICE LIEUTENANT', 59242.59, 59242.59, 1, 2011),
 ('INSTITUTIONAL POLICE OFFICER',
  945970.7899999999,
  72766.98384615385,
  13,
  2011),
 ('INSTITUTIONAL POLICE SERGEANT', 253944.14, 126972.07, 2, 2011),
 ('Inspector, (Police Department)',
  1038216.4199999999,
  173036.06999999998,
  6,
  2012),
 ('Institutional Police Officer', 3872759.04, 104669.16324324324, 37, 2012),
 ('Institutional Police Sergeant', 1030338.99, 171723.165, 6, 2012),
 ('LIEUTENANT I, (POLICE DEPARTMENT)', 153795.73, 153795.73, 1, 2011),
 ('LIEUTENANT II (POLICE DEPARTMENT)', 152985.39, 152985.39, 1, 2011),
 ('LIEUTENANT III (POLICE DEPARTMENT)',
  16364067.01,
  166980.2756122449,
  98,
  2011),
 ('Lieutenant (Police Department)', 186913.98, 186913.98, 1, 2014),
 ('POLICE COMMUNICATIONS SHIFT SUPERVISOR', 791762.62, 98970.3275, 8, 2011),
 ('POLICE OFFICER I', 53314221.08, 114163.21430406852, 467, 2011),
 ('POLICE OFFICER II', 44505070.47, 123282.74368421052, 361, 2011),
 ('POLICE OFFICER III', 99582994.42, 127834.39591784339, 779, 2011),
 ('POLICE SERVICES AIDE', 71185.38, 35592.69, 2, 2011),
 ('Police Officer', 183158895.79, 124091.39281165312, 1476, 2012),
 ('Police Officer 2', 195579360.93, 171410.48284837863, 1141, 2012),
 ('Police Officer 3', 406090319.74, 167736.6046014044, 2421, 2012),
 ('Police Services Aide', 60968.55, 60968.55, 1, 2012),
 ('SENIOR DEPUTY SHERIFF', 10095303.68, 109731.56173913043, 92, 2011),
 ('SENIOR POLICE COMMUNICATIONS DISPATCHER',
  2305094.91,
  96045.62125000001,
  24,
  2011),
 ('SERGEANT I (POLICE DEPARTMENT)', 2510637.2, 147684.5411764706, 17, 2011),
 ('SERGEANT II (POLICE DEPARTMENT)', 2790232.37, 146854.3352631579, 19, 2011),
 ('SERGEANT III (POLICE DEPARTMENT)',
  44640276.48,
  151322.97111864405,
  295,
  2011),
 ('SHERIFF', 197233.84, 197233.84, 1, 2011),
 ("SHERIFF'S CADET", 1875975.69, 29312.12015625, 64, 2011),
 ("SHERIFF'S CAPTAIN", 1204194.82, 150524.3525, 8, 2011),
 ("SHERIFF'S LIEUTENANT", 4981652.05, 134639.24459459458, 37, 2011),
 ("SHERIFF'S PROPERTY KEEPER", 118665.36, 10787.76, 11, 2011),
 ("SHERIFF'S SERGEANT", 6536557.9, 118846.50727272728, 55, 2011),
 ('Senior Deputy Sheriff', 40370752.36, 161483.00944, 250, 2012),
 ('Sergeant, (Police Department)', 7223127.51, 190082.30289473684, 38, 2012),
 ('Sheriff', 19891.46, 19891.46, 1, 2012),
 ('Sheriff (SFERS)', 855716.57, 285238.85666666663, 3, 2012),
 ("Sheriff's Cadet", 9575232.02, 51479.74204301075, 186, 2012),
 ("Sheriff's Captain", 4897961.18, 212954.83391304346, 23, 2012),
 ("Sheriff's Lieutenant", 19366823.19, 188027.4096116505, 103, 2012),
 ("Sheriff's Property Keeper", 479597.89, 18446.072692307695, 26, 2012),
 ("Sheriff's Sergeant", 25942123.42, 169556.36222222223, 153, 2012),
 ('UNDERSHERIFF', 217201.91, 108600.955, 2, 2011),
 ('Undersheriff', 666882.12, 166720.53, 4, 2012),
 ('Undersheriff (SFERS)', 175627.17, 175627.17, 1, 2014)]

In [ ]:
query = """SELECT JobTitle, SUM(TotalPayBenefits), AVG(TotalPayBenefits), COUNT(JobTitle) from Salaries 
WHERE Year = '2011' AND (JobTitle LIKE '%Police%' OR JobTitle LIKE '%Sheriff%') 
GROUP By JobTitle Order by JobTitle"""
cur.execute(query)
cur.fetchall()

[('AIRPORT POLICE SERVICES AIDE', 11244297.15, 60129.93128342246, 187),
 ('ASSISTANT INSPECTOR (POLICE DEPARTMENT)', 188999.2, 188999.2, 1),
 ('ASSISTANT INSPECTOR II (POLICE DEPARTMENT)', 1508888.61, 150888.861, 10),
 ('ASSISTANT INSPECTOR III (POLICE DEPARTMENT)',
  1374040.94,
  152671.21555555554,
  9),
 ('ASSISTANT SHERIFF', 189675.09, 94837.545, 2),
 ('CAPTAIN III (POLICE DEPARTMENT)', 7836004.05, 211783.89324324325, 37),
 ('CHIEF DEPUTY SHERIFF', 503875.24, 167958.41333333333, 3),
 ('CHIEF OF POLICE', 267992.59, 267992.59, 1),
 ('COMMANDER III, (POLICE DEPARTMENT)', 1435955.55, 205136.50714285715, 7),
 ('DEPUTY CHIEF III (POLICE DEPARTMENT)', 1250132.44, 250026.48799999998, 5),
 ('DEPUTY SHERIFF', 64951787.99, 94820.12845255475, 685),
 ('INSPECTOR II, (POLICE DEPARTMENT)',
  432848.20999999996,
  144282.73666666666,
  3),
 ('INSPECTOR III, (POLICE DEPARTMENT)', 24968457.92, 154126.28345679014, 162),
 ('INSPECTOR, (POLICE DEPARTMENT)', 318997.97, 159498.985, 2),
 ('INSTITUTIONAL POLICE LIEUTENANT', 59242.59, 59242.59, 1),
 ('INSTITUTIONAL POLICE OFFICER', 945970.7899999999, 72766.98384615385, 13),
 ('INSTITUTIONAL POLICE SERGEANT', 253944.14, 126972.07, 2),
 ('LIEUTENANT I, (POLICE DEPARTMENT)', 153795.73, 153795.73, 1),
 ('LIEUTENANT II (POLICE DEPARTMENT)', 152985.39, 152985.39, 1),
 ('LIEUTENANT III (POLICE DEPARTMENT)', 16364067.01, 166980.2756122449, 98),
 ('POLICE COMMUNICATIONS SHIFT SUPERVISOR', 791762.62, 98970.3275, 8),
 ('POLICE OFFICER I', 53314221.08, 114163.21430406852, 467),
 ('POLICE OFFICER II', 44505070.47, 123282.74368421052, 361),
 ('POLICE OFFICER III', 99582994.42, 127834.39591784339, 779),
 ('POLICE SERVICES AIDE', 71185.38, 35592.69, 2),
 ('SENIOR DEPUTY SHERIFF', 10095303.68, 109731.56173913043, 92),
 ('SENIOR POLICE COMMUNICATIONS DISPATCHER',
  2305094.91,
  96045.62125000001,
  24),
 ('SERGEANT I (POLICE DEPARTMENT)', 2510637.2, 147684.5411764706, 17),
 ('SERGEANT II (POLICE DEPARTMENT)', 2790232.37, 146854.3352631579, 19),
 ('SERGEANT III (POLICE DEPARTMENT)', 44640276.48, 151322.97111864405, 295),
 ('SHERIFF', 197233.84, 197233.84, 1),
 ("SHERIFF'S CADET", 1875975.69, 29312.12015625, 64),
 ("SHERIFF'S CAPTAIN", 1204194.82, 150524.3525, 8),
 ("SHERIFF'S LIEUTENANT", 4981652.05, 134639.24459459458, 37),
 ("SHERIFF'S PROPERTY KEEPER", 118665.36, 10787.76, 11),
 ("SHERIFF'S SERGEANT", 6536557.9, 118846.50727272728, 55),
 ('UNDERSHERIFF', 217201.91, 108600.955, 2)]

In [ ]:
query = """SELECT JobTitle, SUM(TotalPayBenefits), AVG(TotalPayBenefits), COUNT(JobTitle) from Salaries 
WHERE Year = '2012' AND (JobTitle LIKE '%Police%' OR JobTitle LIKE '%Sheriff%') 
GROUP By JobTitle Order by JobTitle"""
cur.execute(query)
cur.fetchall()

[('Assistant Sheriff', 261249.93, 130624.965, 2),
 ('Chief Deputy Sheriff', 772327.6, 193081.9, 4),
 ('Chief of Police', 391362.3, 391362.3, 1),
 ('Community Police Services Aide', 17022524.97, 95097.90486033518, 179),
 ('Deputy Sheriff', 90260344.97, 136139.2835143288, 663),
 ('Deputy Sheriff 1', 291234.74, 32359.415555555555, 9),
 ('Inspector, (Police Department)', 389651.99, 194825.995, 2),
 ('Institutional Police Officer', 1284354.38, 107029.53166666666, 12),
 ('Institutional Police Sergeant', 349038.82999999996, 174519.41499999998, 2),
 ('Police Officer', 51445336.71, 122781.23319809069, 419),
 ('Police Officer 2', 68668793.7, 162337.57375886524, 423),
 ('Police Officer 3', 138076018.47, 159810.2065625, 864),
 ('Police Services Aide', 60968.55, 60968.55, 1),
 ('Senior Deputy Sheriff', 13674136.34, 155387.91295454546, 88),
 ('Sergeant, (Police Department)', 2842573.24, 177660.8275, 16),
 ('Sheriff', 19891.46, 19891.46, 1),
 ('Sheriff (SFERS)', 256636.3, 256636.3, 1),
 ("Sheriff's Cadet", 3268921.0, 54482.01666666667, 60),
 ("Sheriff's Captain", 1441471.1400000001, 205924.4485714286, 7),
 ("Sheriff's Lieutenant", 6508994.6899999995, 185971.27685714283, 35),
 ("Sheriff's Property Keeper", 133166.68, 13316.668, 10),
 ("Sheriff's Sergeant", 8195631.98, 163912.6396, 50),
 ('Undersheriff', 253521.25, 126760.625, 2)]

In [ ]:
query = """SELECT JobTitle, SUM(TotalPayBenefits), AVG(TotalPayBenefits), COUNT(JobTitle) from Salaries 
WHERE Year = '2013' AND (JobTitle LIKE '%Police%' OR JobTitle LIKE '%Sheriff%') 
GROUP By JobTitle Order by JobTitle"""
cur.execute(query)
cur.fetchall()

[('Assistant Sheriff', 246135.72, 246135.72, 1),
 ('Chief Deputy Sheriff', 702560.07, 234186.68999999997, 3),
 ('Chief of Police', 425815.28, 425815.28, 1),
 ('Community Police Services Aide', 16505787.14, 93253.03468926554, 177),
 ('Deputy Sheriff', 93750724.8, 143569.25696784072, 653),
 ('Deputy Sheriff 1', 2388737.16, 54289.48090909091, 44),
 ('Inspector, (Police Department)', 428154.08999999997, 142718.03, 3),
 ('Institutional Police Officer', 1324675.09, 101898.08384615385, 13),
 ('Institutional Police Sergeant', 320286.06000000006, 160143.03000000003, 2),
 ('Police Officer', 64347754.07, 127927.94049701789, 503),
 ('Police Officer 2', 68171160.25, 177992.5855091384, 383),
 ('Police Officer 3', 134598825.71, 173900.2916149871, 774),
 ('Senior Deputy Sheriff', 13398366.82, 161426.10626506025, 83),
 ('Sergeant, (Police Department)', 2605813.9, 200447.22307692308, 13),
 ('Sheriff (SFERS)', 298551.11, 298551.11, 1),
 ("Sheriff's Cadet", 2725059.54, 56772.07375, 48),
 ("Sheriff's Captain", 1732081.31, 216510.16375, 8),
 ("Sheriff's Lieutenant", 6555579.45, 187302.27000000002, 35),
 ("Sheriff's Property Keeper", 170403.80000000002, 18933.75555555556, 9),
 ("Sheriff's Sergeant", 9088240.58, 171476.23735849056, 53),
 ('Undersheriff', 263145.77, 263145.77, 1)]

In [ ]:
query = """SELECT JobTitle, SUM(TotalPayBenefits), AVG(TotalPayBenefits), COUNT(JobTitle) from Salaries 
WHERE Year = '2014' AND (JobTitle LIKE '%Police%' OR JobTitle LIKE '%Sheriff%') 
GROUP By JobTitle Order by JobTitle"""
cur.execute(query)
cur.fetchall()

[('Assistant Sheriff', 259793.64, 259793.64, 1),
 ('Chief Deputy Sheriff', 706246.81, 235415.60333333336, 3),
 ('Chief of Police', 418019.22, 418019.22, 1),
 ('Community Police Services Aide', 18266013.95, 89980.36428571428, 203),
 ('Deputy Sheriff', 92239944.64, 149497.4791572123, 617),
 ('Deputy Sheriff (SFERS)', 1981418.08, 123838.63, 16),
 ('Deputy Sheriff 1', 2335930.6, 93437.224, 25),
 ('Inspector, (Police Department)', 220410.34, 220410.34, 1),
 ('Institutional Police Officer', 1263729.57, 105310.7975, 12),
 ('Institutional Police Sergeant', 361014.1, 180507.05, 2),
 ('Lieutenant (Police Department)', 186913.98, 186913.98, 1),
 ('Police Officer', 67365805.01, 121598.92601083033, 554),
 ('Police Officer 2', 58739406.98, 175341.5133731343, 335),
 ('Police Officer 3', 133415475.56, 170390.1348148148, 783),
 ('Senior Deputy Sheriff', 13298249.2, 168332.26835443036, 79),
 ('Sergeant, (Police Department)', 1774740.37, 197193.37444444446, 9),
 ('Sheriff (SFERS)', 300529.16, 300529.16, 1),
 ("Sheriff's Cadet", 3581251.48, 45913.48051282051, 78),
 ("Sheriff's Captain", 1724408.73, 215551.09125, 8),
 ("Sheriff's Lieutenant", 6302249.05, 190977.24393939393, 33),
 ("Sheriff's Property Keeper", 176027.41, 25146.772857142856, 7),
 ("Sheriff's Sergeant", 8658250.86, 173165.0172, 50),
 ('Undersheriff', 150215.1, 150215.1, 1),
 ('Undersheriff (SFERS)', 175627.17, 175627.17, 1)]

In [56]:
query = """SELECT SUM(TotalPayBenefits), AVG(TotalPayBenefits), Count(Year), Year from Salaries 
WHERE JobTitle LIKE '%Police%' OR  JobTitle LIKE '%Sheriff%' 
Group by Year Order by Year"""
cur.execute(query)
cur.fetchall()

[(410140218.78, 118127.9431970046, 3472, 2011),
 (405868151.22, 142359.92676955456, 2851, 2012),
 (420047857.72, 149589.69292022794, 2808, 2013),
 (413901671.01, 146721.61326125488, 2821, 2014)]

### First Discussion

Interestingly, 2011 seems to be anomalous compared to the other three years. 2012-2014 all have and average pay and benefits between 140 and 150 thousand, with a total staff of around 2800, and a total budget for staff of 400-420 million. 2011 has a similar budget with 600 more staff and an average salary with benefits of a bit below 120000. Quickly looking over the job titles for each year reveals that 2011 uniquely has *AIRPORT POLICE SERVICES AIDE*, *'POLICE COMMUNICATIONS SHIFT SUPERVISOR*, and *SENIOR POLICE COMMUNICATIONS DISPATCHER* which account for around 200 employees and around 15 million in pay and benefits. An additional 45 million in pay and benefits can be found with the Sergeant III position found in the 2011 data set across 300 employees. The first set of positions have a lower average pay and benefits than 140,000. 

It's highly likely that the positions were renamed so trying to match **Police** and **Sheriff** won't pick it up, though the Sergeant III position was probably just absorbed under another job title. This means it would be good to rerun the previous SQL query removing the aforementioned positions to see how the numbers compare.

In [32]:
query = """SELECT  SUM(TotalPayBenefits), AVG(TotalPayBenefits), Count(Year), Year from Salaries 
WHERE (JobTitle LIKE '%Police%' OR JobTitle LIKE '%Sheriff%') 
AND (JobTitle NOT LIKE '%communications%' AND Jobtitle NOT LIKE '%airport%') 
GROUP By Year Order by Year"""
cur.execute(query)
cur.fetchall()

[(395799064.1, 121672.01478635106, 3253, 2011),
 (405868151.22, 142359.92676955456, 2851, 2012),
 (420047857.72, 149589.69292022794, 2808, 2013),
 (413901671.01, 146721.61326125488, 2821, 2014)]

In [ ]:
query = """SELECT JobTitle, COUNT(JobTitle) from Salaries 
WHERE Jobtitle LIKE '%Captain%' OR Jobtitle LIKE '%Lieutenant%' OR Jobtitle LIKE '%cadet%' 
GROUP By JobTitle Order by JobTitle"""
df = pd.read_sql_query(query, con)
df.head()

                                            JobTitle  COUNT(JobTitle)
0                    CAPTAIN III (POLICE DEPARTMENT)               37
1  CAPTAIN, BUREAU OF FIRE PREVENTION AND PUBLIC ...                1
2              CAPTAIN, EMERGENCYCY MEDICAL SERVICES               24
3                          CAPTAIN, FIRE SUPPRESSION               71
4                                          Captain 3              101

In [ ]:
query = """SELECT JobTitle, COUNT(JobTitle) from Salaries 
WHERE Jobtitle LIKE '%Captain%' OR Jobtitle LIKE '%CPT%' OR Jobtitle LIKE '%cadet%' 
GROUP By JobTitle Order by JobTitle"""
cur.execute(query)
cur.fetchall()

[('CAPTAIN III (POLICE DEPARTMENT)', 37),
 ('CAPTAIN, BUREAU OF FIRE PREVENTION AND PUBLIC SAFE', 1),
 ('CAPTAIN, EMERGENCYCY MEDICAL SERVICES', 24),
 ('CAPTAIN, FIRE SUPPRESSION', 71),
 ('Captain 3', 101),
 ('Captain, (Fire Department)', 1),
 ('Captain, Emergency Med Svcs', 75),
 ('Captain, Fire Suppression', 211),
 ("SHERIFF'S CADET", 64),
 ("SHERIFF'S CAPTAIN", 8),
 ("Sheriff's Cadet", 186),
 ("Sheriff's Captain", 23)]

In [ ]:
query = """SELECT JobTitle, COUNT(JobTitle) from Salaries 
WHERE Jobtitle LIKE '%Sergeant%' 
GROUP By JobTitle Order by JobTitle"""
cur.execute(query)
cur.fetchall()

[('INSTITUTIONAL POLICE SERGEANT', 2),
 ('Institutional Police Sergeant', 6),
 ('SERGEANT I (POLICE DEPARTMENT)', 17),
 ('SERGEANT II (POLICE DEPARTMENT)', 19),
 ('SERGEANT III (POLICE DEPARTMENT)', 295),
 ("SHERIFF'S SERGEANT", 55),
 ('Sergeant 2', 131),
 ('Sergeant 3', 1047),
 ('Sergeant, (Police Department)', 38),
 ("Sheriff's Sergeant", 153)]

In [ ]:
query = """SELECT JobTitle, COUNT(JobTitle) from Salaries 
WHERE Year='2012' AND (Jobtitle LIKE '%Sergeant%' OR Jobtitle LIKE '%SGT%') 
GROUP By JobTitle Order by JobTitle"""
cur.execute(query)
cur.fetchall()

[('Institutional Police Sergeant', 2),
 ('Sergeant 2', 22),
 ('Sergeant 3', 317),
 ('Sergeant, (Police Department)', 16),
 ("Sheriff's Sergeant", 50)]

In [ ]:
query = """SELECT JobTitle, COUNT(JobTitle) from Salaries 
WHERE Year='2013' AND (Jobtitle LIKE '%Sergeant%' OR Jobtitle LIKE '%SGT%') 
GROUP By JobTitle Order by JobTitle"""
cur.execute(query)
cur.fetchall()

[('Capt,Fire Prev or Fire Invsgtn', 7),
 ('Institutional Police Sergeant', 2),
 ('Sergeant 2', 55),
 ('Sergeant 3', 361),
 ('Sergeant, (Police Department)', 13),
 ("Sheriff's Sergeant", 53)]

In [ ]:
query = """SELECT JobTitle, COUNT(JobTitle) from Salaries 
WHERE Year='2014' AND (Jobtitle LIKE '%Sergeant%' OR Jobtitle LIKE '%SGT%') 
GROUP By JobTitle Order by JobTitle"""
cur.execute(query)
cur.fetchall()

[('Capt,Fire Prev or Fire Invsgtn', 7),
 ('Institutional Police Sergeant', 2),
 ('Sergeant 2', 54),
 ('Sergeant 3', 369),
 ('Sergeant, (Police Department)', 9),
 ("Sheriff's Sergeant", 50)]

In [ ]:
query = """SELECT Year, SUM(TotalPayBenefits), AVG(TotalPayBenefits), COUNT(JobTitle) from Salaries 
WHERE Jobtitle LIKE '%Sergeant%' OR Jobtitle LIKE '&SGT%' 
GROUP By Year Order by JobTitle"""
cur.execute(query)
cur.fetchall()

[(2011, 56731648.09, 146215.58786082474, 388),
 (2012, 76630901.02, 188282.31208845208, 407),
 (2013, 98967307.4, 204477.9078512397, 484),
 (2014, 97891786.55, 202255.75733471074, 484)]

In [ ]:
query = """SELECT Year, SUM(TotalPayBenefits), AVG(TotalPayBenefits), COUNT(JobTitle) from Salaries 
WHERE Jobtitle LIKE '%lieutenant%' 
GROUP By Year Order by JobTitle"""
cur.execute(query)
cur.fetchall()

[(2011, 51151974.97, 161873.33851265823, 316),
 (2012, 70384376.46, 213285.98927272725, 330),
 (2013, 74491359.92, 226417.5073556231, 329),
 (2014, 71893239.42, 219857.00128440367, 327)]

In [ ]:
query = """SELECT Year, SUM(TotalPayBenefits), AVG(TotalPayBenefits), COUNT(JobTitle) from Salaries 
WHERE Jobtitle LIKE '%captain%' 
GROUP By Year Order by JobTitle"""
cur.execute(query)
cur.fetchall()

[(2011, 26186044.27, 185716.6260283688, 141),
 (2012, 33575285.82, 243299.17260869566, 138),
 (2014, 34926113.26, 247702.9309219858, 141),
 (2013, 33892915.55, 256764.51174242422, 132)]

The difference in employment from year to year becomes less significant when taking a title like *sergeant* or *captian* makes the difference smaller. There is a somewhat constant amount of captains, lieutenants, and sergeants over time though the benefits are much worse in 2011. This may be due to budget cuts in 2011 and 2012 as per a [San Francisco Gate Article](https://www.sfgate.com/bayarea/article/Police-staffing-expected-to-shrink-2459144.php#ixzz1Gb2OcXrN), or that there is any aspect that I am missing for this. I figure budget cuts are more likely since the average pay benefits are much lower even for effectively the same position (within sergeants or captains for example).

Aside from the quirks of 2011, the distribution and compenssation of posiitions is basically consistent. There are differences, of course, like the fact that 2014 had an uptick in the number of Community Police Services Aides, and Sheriff's Cadets (each increased by about 30) as well as a loss of around 50 Police Officer II's without that being fully reflected in other roles such as Police Officer III's (which did have a bit of an uptick), or Police Sergeants. The changes between 2012 and 2013 are fairly minimal, with a decently signficant decrease of Sheriff's Cadets (from 60 down to 48), albeit with a parallel increase of Deputy Sherriff 1's from 9 to 44.

Basically, the number of personnel is basically constant, which can be seen from the previous look into captains, sergeants, and lieutenants, and from ignoring the positions such as *AIRPORT POLICE SERVICES AIDE* in 2011 which were likely absorbed into other positions either in or out of the police department.

What's left is taking a look at Status (Number of full time versus part time employees), portion of overtime pay, benefits pay, and base pay. It is important to note that most jobs are not actually labeled as full or part time so that will be a minimally important aspect of the comparison.

In [ ]:
query = """SELECT AVG(TotalPayBenefits), Status, COUNT(Status) from Salaries 
WHERE (JobTitle LIKE '%Police%' OR JobTitle LIKE '%Sheriff%') 
GROUP By Status Order by JobTitle"""
cur.execute(query)
cur.fetchall()

[(135369.2068470047, '', 9131),
 (163835.18180519482, 'FT', 2310),
 (69358.90614481409, 'PT', 511)]

In [55]:
query = """SELECT Year, JobTitle, AVG(BasePay), AVG(OvertimePay), AVG(OtherPay), AVG(Benefits), COUNT(JobTitle) from Salaries 
WHERE (JobTitle LIKE '%Police%' OR JobTitle LIKE '%Sheriff%') 
GROUP By JobTitle Order by JobTitle"""
df = pd.read_sql_query(query, con)
df.head()

,Year,JobTitle,AVG(BasePay),AVG(OvertimePay),AVG(OtherPay),AVG(Benefits),COUNT(JobTitle)
0,2011,AIRPORT POLICE SERVICES AIDE,51178.742834,5478.936096,3472.252353,0.0,187
1,2011,ASSISTANT INSPECTOR (POLICE DEPARTMENT),123169.950000,45679.840000,20149.410000,0.0,1
2,2011,ASSISTANT INSPECTOR II (POLICE DEPARTMENT),127866.102000,13547.629000,9475.130000,0.0,10
3,2011,ASSISTANT INSPECTOR III (POLICE DEPARTMENT),130479.954444,13373.892222,8817.368889,0.0,9
4,2011,ASSISTANT SHERIFF,94400.405000,0.000000,437.140000,0.0,2

## Fire Department Jobs

In [44]:
query = """SELECT JobTitle, SUM(TotalPayBenefits), Year from Salaries WHERE JobTitle LIKE '%Fire%' Group by JobTitle Order by Year"""
cur.execute(query)
cur.fetchall()

[('ASSISTANT CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)', 610283.55, 2011),
 ('BATTALION CHIEF, (FIRE DEPARTMENT)', 9749499.16, 2011),
 ('CAPTAIN, BUREAU OF FIRE PREVENTION AND PUBLIC SAFE', 206704.63, 2011),
 ('CAPTAIN, FIRE SUPPRESSION', 12762877.81, 2011),
 ('CHIEF FIRE ALARM DISPATCHER', 112798.37, 2011),
 ('CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)', 302377.73, 2011),
 ('DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)', 838078.68, 2011),
 ('FIRE ALARM DISPATCHER', 130371.56999999999, 2011),
 ('FIRE FIGHTER PARAMEDIC', 38957981.84, 2011),
 ('FIRE PROTECTION ENGINEER', 507207.46, 2011),
 ('FIRE RESCUE PARAMEDIC', 566616.29, 2011),
 ('FIRE SAFETY INSPECTOR II', 1678561.17, 2011),
 ('FIREFIGHTER', 110597884.48, 2011),
 ('INSPECTOR, BUREAU OF FIRE PREVENTION AND PUBLIC SA', 3220814.25, 2011),
 ('INVESTIGATOR, BUREAU OF FIRE INVESTIGATION', 702051.63, 2011),
 ('LIEUTENANT, BUREAU OF FIRE PREVENTION AND PUBLIC S', 1534524.46, 2011),
 ('LIEUTENANT, FIRE DEPARTMENT', 27905707.74, 2011),
 ('MARINE ENGINEER OF FIRE BOATS', 639837.8099999999, 2011),
 ('PILOT OF FIRE BOATS', 539087.3099999999, 2011),
 ('Asst Chf of Dept (Fire Dept)', 6166755.91, 2012),
 ('Battlion Chief, Fire Suppressi', 9671884.74, 2012),
 ('Captain, Fire Suppression', 52758713.7, 2012),
 ('Chief Fire Alarm Dispatcher', 457337.63, 2012),
 ('Chief, Fire Department', 1226595.98, 2012),
 ('Dep Chf of Dept (Fire Dept)', 2287265.7, 2012),
 ('EMT/Paramedic/Firefighter', 154131449.64, 2012),
 ('Fire Alarm Dispatcher', 949089.88, 2012),
 ('Fire Protection Engineer', 2066197.58, 2012),
 ('Fire Rescue Paramedic', 1770222.44, 2012),
 ('Fire Safety Inspector 2', 6358934.6, 2012),
 ('Firefighter', 431972718.89, 2012),
 ('Insp, Fire Dept', 15313202.39, 2012),
 ('Invstgtor,Fire Dept', 1605224.35, 2012),
 ('Lieut,Fire Prev', 6732775.12, 2012),
 ('Lieutenant, Fire Suppression', 128682376.83, 2012),
 ('Marine Engineer of Fire Boats', 2434031.31, 2012),
 ('Pilot of Fire Boats', 2233749.04, 2012),
 ('Battalion Chief, Fire Suppress', 19952045.93, 2013),
 ('Capt,Fire Prev or Fire Invsgtn', 3579647.54, 2013),
 ('Captain, (Fire Department)', 35332.78, 2013)]

In [45]:
query = """SELECT SUM(TotalPayBenefits), AVG(TotalPayBenefits), Count(Year), Year from Salaries WHERE JobTitle LIKE '%Fire%' Group by Year Order by Year"""
cur.execute(query)
cur.fetchall()

[(211563265.94, 145005.66548320767, 1459, 2011),
 (273810371.21, 188965.05949620425, 1449, 2012),
 (291038363.49, 199341.3448561644, 1460, 2013),
 (285536817.28, 188972.0829119788, 1511, 2014)]

## Healthcare Jobs

In [46]:
query = """SELECT JobTitle, SUM(TotalPayBenefits), Year from Salaries WHERE JobTitle LIKE '%nurs%' OR JobTitle LIKE '%medical%' OR JobTitle LIKE '%dent%' OR JobTitle LIKE '%pharma%' 
OR JobTitle LIKE '%physician%' OR JobTitle LIKE '%social work%' Group by JobTitle Order by Year"""
cur.execute(query)
cur.fetchall()

[('ADMINISTRATOR, SFGH MEDICAL CENTER', 257124.44, 2011),
 ('ASSISTANT MEDICAL EXAMINER', 1063965.86, 2011),
 ('ASSISTANT SUPERINTENDENT RECREATION', 100515.4, 2011),
 ('BUILDINGS AND GROUNDS MAINTENANCE SUPERINTENDENT', 1617180.56, 2011),
 ('CAPTAIN, EMERGENCYCY MEDICAL SERVICES', 4176262.96, 2011),
 ('CHIEF NURSERY SPECIALIST', 84800.16, 2011),
 ('CITY SHOPS ASSISTANT SUPERINTENDENT', 211724.7, 2011),
 ('CLINICAL NURSE SPECIALIST', 3464581.28, 2011),
 ('CLINICAL PHARMACIST', 4326965.74, 2011),
 ('CONFIDENTIAL CHIEF ATTORNEY II (CIVIL & CRIMINAL)', 644966.04, 2011),
 ('CONFIDENTIAL SECRETARY CITY ATTORNEY', 78482.26, 2011),
 ('CONFIDENTIAL SECRETARY TO DISTRICT ATTORNEY', 81650.52, 2011),
 ('DENTAL AIDE', 839839.18, 2011),
 ('DENTAL HYGIENIST', 245250.97999999998, 2011),
 ('DENTIST', 940939.01, 2011),
 ('EMERGENCY MEDICAL SERVICES AGENCY SPECIALIST', 434689.06, 2011),
 ('INCIDENT SUPPORT SPECIALIST', 1085669.42, 2011),
 ('LICENSED VOCATIONAL NURSE', 11591302.27, 2011),
 ('MECHANICAL SHOP AND EQUIPMENT SUPERINTENDENT', 407357.84, 2011),
 ('MEDICAL EVALUATIONS ASSISTANT', 7349252.16, 2011),
 ("MEDICAL EXAMINER'S INVESTIGATOR I", 207432.05, 2011),
 ("MEDICAL EXAMINER'S INVESTIGATOR II", 830581.27, 2011),
 ("MEDICAL EXAMINER'S INVESTIGATOR III", 212376.78999999998, 2011),
 ('MEDICAL RECORDS CLERK', 2425646.12, 2011),
 ('MEDICAL RECORDS TECHNICIAN', 2310336.89, 2011),
 ('MEDICAL RECORDS TECHNICIAN SUPERVISOR', 463859.91000000003, 2011),
 ('MEDICAL SOCIAL WORK SUPERVISOR', 279446.99, 2011),
 ('MEDICAL SOCIAL WORKER', 5773414.94, 2011),
 ('MEDICAL STAFF SERVICES DEPARTMENT ANALYST', 157824.06, 2011),
 ('MEDICAL STAFF SERVICES DEPARTMENT SPECIALIST', 239695.83, 2011),
 ('MEDICAL TRANSCRIBER TYPIST', 288274.31, 2011),
 ('NURSE MANAGER', 13226873.2, 2011),
 ('NURSE MIDWIFE', 619265.27, 2011),
 ('NURSE PRACTITIONER', 18511994.55, 2011),
 ('NURSERY SPECIALIST', 343548.54000000004, 2011),
 ('NURSES STAFFING ASSISTANT', 786541.65, 2011),
 ('NURSING ASSISTANT', 8763814.85, 2011),
 ('NURSING SUPERVISOR', 4403712.41, 2011),
 ('NURSING SUPERVISOR PSYCHIATRIC', 866394.54, 2011),
 ('OPERATING ROOM NURSE', 224978.88, 2011),
 ('PHARMACIST', 4535594.44, 2011),
 ('PHARMACY HELPER', 381409.78, 2011),
 ('PHARMACY TECHNICIAN', 3890791.34, 2011),
 ('PHYSICIAN ASSISTANT', 1767990.99, 2011),
 ('PHYSICIAN SPECIALIST', 7669824.23, 2011),
 ('PSYCHIATRIC SOCIAL WORKER', 8176640.66, 2011),
 ('PUBLIC HEALTH NURSE', 5728069.39, 2011),
 ('REGISTERED NURSE', 129971170.5, 2011),
 ('SENIOR MEDICAL SOCIAL WORKER', 390880.36, 2011),
 ('SENIOR MEDICAL TRANSCRIBER TYPIST', 60422.59, 2011),
 ('SENIOR PHARMACY HELPER', 59483.8, 2011),
 ('SENIOR PHYSICIAN SPECIALIST', 16080714.24, 2011),
 ('SENIOR PSYCHIATRIC SOCIAL WORKER', 2177048.57, 2011),
 ('SENIOR SOCIAL WORKER', 8643057.38, 2011),
 ('SEWAGE TREATMENT PLANT SUPERINTENDENT', 879367.34, 2011),
 ('SOCIAL WORK SPECIALIST', 1403022.06, 2011),
 ('SOCIAL WORK SUPERVISOR', 1202337.43, 2011),
 ('SOCIAL WORKER', 1394240.89, 2011),
 ('SPECIAL NURSE', 43917756.47, 2011),
 ('STUDENT DESIGN TRAINEE 1/ARC-ENG-PLNG', 1366621.1, 2011),
 ('STUDENT DESIGN TRAINEE 2/ARC-ENG-PLNG', 869336.41, 2011),
 ('STUDENT DESIGN TRAINEE 3/ARC-ENG-PLNG', 934204.37, 2011),
 ('SUPERINTENDENT OF WATER TREATMENT FACILITIES', 253414.2, 2011),
 ('SUPERVISING PHARMACIST', 1080193.64, 2011),
 ('SUPERVISING PHYSICIAN SPECIALIST', 3607940.14, 2011),
 ('SUPPLY ROOM ATTENDENT', 46854.36, 2011),
 ('TRACK MAINTENANCE SUPERINTENDENT,MUNICIPAL RAILWAY', 92314.64, 2011),
 ('WATER CONSTRUCTION AND MAINTENANCE SUPERINTENDENT', 300705.37, 2011),
 ('Adm, SFGH Medical Center', 1041239.12, 2012),
 ('Asst Superintendent Rec', 446353.9, 2012),
 ('Chief Nursery Specialist', 281776.61, 2012),
 ('Clinical Nurse Specialist', 13847920.48, 2012),
 ('Clinical Pharmacist', 22925164.76, 2012),
 ('Dental Aide', 3971933.23, 2012),
 ('Dental Hygienist', 1159766.82, 2012),
 ('Dentist', 3707464.38, 2012),
 ('Emergency Medical Svcs Chief', 940268.99, 2012),
 ('Incident Support Specialist', 4648998.33, 2012),
 ('Licensed Vocational Nurse', 55606050.12, 2012),
 ('Medical Evaluations Assistant', 41220779.23, 2012),
 ('Medical Records Clerk', 11642821.56, 2012),
 ('Medical Records Tech Sprv', 2149831.22, 2012),
 ('Medical Records Technician', 11351260.89, 2012),
 ('Medical Social Work Supervisor', 1290505.21, 2012),
 ('Medical Social Worker', 28849549.12, 2012),
 ('Medical Transcriber Typist', 1179222.35, 2012),
 ('Nurse Manager', 56737202.01, 2012),
 ('Nurse Midwife', 2427863.01, 2012),
 ('Nurse Practitioner', 84172842.49, 2012),
 ('Nursery Specialist', 1385957.88, 2012),
 ('Nurses Staffing Assistant', 4169077.1, 2012),
 ('Nursing Assistant', 39391661.63, 2012),
 ('Nursing Supervisor', 18772080.73, 2012),
 ('Nursing Supervisor Psychiatric', 3043109.91, 2012),
 ('Operating Room Nurse', 373577.3, 2012),
 ('Pharmacist', 22493786.1, 2012),
 ('Pharmacy Helper', 1410354.95, 2012),
 ('Pharmacy Technician', 19583172.3, 2012),
 ('Physician Assistant', 6912816.74, 2012),
 ('Physician Specialist', 32694720.21, 2012),
 ('Psychiatric Social Worker', 37057591.12, 2012),
 ('Public Health Nurse', 26496560.08, 2012),
 ('Registered Nurse', 566569738.88, 2012),
 ('Senior Medical Social Worker', 1817191.17, 2012),
 ('Senior Pharmacy Helper', 308710.12, 2012),
 ('Senior Physician Specialist', 67407407.67, 2012),
 ('Senior Social Worker', 23692697.29, 2012),
 ('Social Work Specialist', 9481793.84, 2012),
 ('Social Work Supervisor', 6537843.06, 2012),
 ('Social Worker', 9184773.41, 2012),
 ('Special Nurse', 159637923.59, 2012),
 ('Sr Medical Transcriber Typist', 265584.57, 2012),
 ('Sr Psychiatric Social Worker', 9602207.85, 2012),
 ('Supervising Pharmacist', 4217263.64, 2012),
 ('Supervising Physician Spec', 12711843.73, 2012),
 ('City Shops Asst Superintendent', 300530.11, 2013),
 ('HSA Social Worker', 13337301.92, 2014)]